version: '3.8'

services:
  app:
    container_name: vue-maximage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./public:/usr/share/nginx/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
